<div class="container">
    <h1>Tasks</h1>
    <table class="table table-responsive">
        <thead class="thead-inverse">
            <tr>
                <th>#</th>
                <th colspan="6">Tasks</th>
            </tr>
        </thead>
        <tbody>
            <tr id="last-row">
                <td colspan="5">
                    <input id="libelle" name="libelle" type="text" class="form-control" placeholder="Enter a new task">
                </td>
                <td colspan="2"><button class="btn btn-success" id="add">Add</a></button>
            </tr>
        </tbody>
    </table>
</div>
<script src="<?php echo DATA_WEB ?>js/task-service.js"></script>
