<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <title>Go rate games!</title>
        <link href="<?php echo DATA_WEB ?>css/tether.min.css" rel="stylesheet">
        <link href="<?php echo DATA_WEB ?>css/bootstrap.min.css" rel="stylesheet">
        <link href="<?php echo DATA_WEB ?>css/global.css" rel="stylesheet">
    </head>
    <body>
        <header>
            <nav class="navbar navbar-toggleable-md navbar-inverse bg-inverse fixed-top">
                <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <a class="navbar-brand" href="<?= LINK_WEB ?>">Gamenote <?php if ($helpers->isAuthenticated()) : ?>
                    <span class="nav-message xs">Bienvenue <?= $_SESSION['user']->pseudo ?>!</span>
                    <?php endif; ?></a>

                <div class="collapse navbar-collapse" id="navbarsExampleDefault">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item <?= $_SERVER['REQUEST_URI'] === '/Gamenote/' ? 'active' : '' ?>">
                            <a class="nav-link" href="<?= LINK_WEB ?>">Home</a>
                        </li>
                        <?php if (!$helpers->isAuthenticated()) : ?>
                            <li class="nav-item <?= $_SERVER['REQUEST_URI'] === '/Gamenote/user/register' ? 'active' : '' ?>">
                                <a class="nav-link" href="<?= LINK_WEB ?>user/register">Register</a>
                            </li>
                        <?php endif; ?>
                        <?php if ($helpers->isAuthenticated()) : ?>
                            <li class="nav-item <?= $_SERVER['REQUEST_URI'] === '/Gamenote/game/create' ? 'active' : '' ?>">
                                <a class="nav-link" href="<?= LINK_WEB ?>game/create">New game</a>
                            </li>
                            <li class="nav-item <?= $_SERVER['REQUEST_URI'] === '/Gamenote/game/index/' . $_SESSION['user']->id ? 'active' : '' ?>">
                                <a class="nav-link" href="<?= LINK_WEB ?>game/index/<?= $_SESSION['user']->id ?>">My critics</a>
                            </li>
                        <?php endif; ?>
                    </ul>
                    <?php if (!$helpers->isAuthenticated()) : ?>
                        <form method="post" action="<?= LINK_WEB ?>" class="form-inline my-2 my-lg-0">
                            <input class="form-control mr-sm-2 mb-1 mb-sm-0" type="email" name="email" placeholder="email">
                            <input class="form-control mr-sm-2 mb-1 mb-sm-0" type="password" name="password" placeholder="password">
                            <button class="btn btn-outline-success" type="submit">Sign in</button>
                        </form>
                        <?php
                    endif;
                    if ($helpers->isAuthenticated()):
                        ?>
                        <ul class="navbar-nav">
                            <li class="nav-item">
                                <span class="nav-message sm">Bienvenue <?= $_SESSION['user']->pseudo ?>!</span>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-danger" href="<?= LINK_WEB ?>user/logout">Sign out</a>
                            </li>
                        </ul>
                    <?php endif; ?>
                </div>
            </nav>
        </header>
        <main>
            <?= $viewContent ?>
        </main>
        <script src="<?php echo DATA_WEB ?>js/jquery-3.2.1.min.js"></script>
        <script src="<?php echo DATA_WEB ?>js/tether.min.js"></script>
        <script src="<?php echo DATA_WEB ?>js/bootstrap.min.js"></script>
    </body>
</html>
