<div class="container">
    <h1>New critic</h1>
    <hr />
    <?php foreach ($errors as $e) : ?>
        <div class="alert alert-danger">
            <?= $e ?>
        </div>
    <?php endforeach; ?>
    <div class="row">
        <form method='post' class="col col-sm-6 offset-sm-3">
            <?php 
            $c = count($criterias);
            for($i = 0; $i < $c; $i++): ?>
            <fieldset class="form-group">
                <legend><?= ucfirst($criterias[$i]->name) ?></legend>
                <input type="hidden" name="criteria[]" value="<?=$criterias[$i]->id ?>">
                <div class="form-group">
                    <label for="rating">Rating</label>
                    <input value="<?= $helpers->foundInputValue('rating', null, $i) ?>" type="number" min="0" max="5" name="rating[]" class="form-control" id="rating"  placeholder="*/5" required>
                </div>
                <div class="form-group">
                    <label for="note">Note</label>
                    <textarea class="form-control" id="note" name="note[]" rows="5"><?= $helpers->foundInputValue('note', null, $i) ?></textarea>
                </div>
            </fieldset>
            <?php endfor; ?>
            <button type="submit" class="btn btn-primary">Save</button>
        </form>
    </div>
</div>

